### PR TITLE
My first pull request, concerning excessive Title Case

### PR DESCRIPTION
**Pull request by amandafrench**

### CODE REVIEW

**Comment by JohnMcLear** [comment]
Looks fine! Good job. Okay to merge

**Comment by amandafrench** [comment]
Thanks. :) Kind of an in-joke with @boonebgorges, but also good git practice for me ...

**Comment by boonebgorges** [comment]
I reject the intensity of disapproval suggested by 'shudder', but accept the pull request :)

**Comment by JohnMcLear** [comment]
This is why I stopped working in Education, you're all weirdos ;)

**Comment by boonebgorges** [comment]
@JohnMcLear I choose to interpret that as a compliment :-D

**Comment by amandafrench** [comment]
Well, I've just learned that commit messages are supposed to be in the imperative mood, so you yourself may have yet more cause to shudder than I've given you already: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Pull request merged**
